name:                alethe
version:             0.1.0.0
github:              "wearley/alethe-repl"
license:             BSD-3-Clause
author:              "William Earley"
maintainer:          "w.earley@damtp.cam.ac.uk"
copyright:           "2020 William Earley"

#extra-source-files:

synopsis:            Interpreter for alethe
#category:            
#description:         

dependencies:
- base >= 4.7 && < 5
- parsec
- mtl
- containers
- unix
- directory
- filepath
- array
- vector
- heaps
- template-haskell
- raw-strings-qq
- haskeline

executable:
  source-dirs: src
  main: Main.hs
  ghc-options: -Wall -Wno-missing-signatures -O3
  default-extensions:  FlexibleContexts, TupleSections, LambdaCase, NoMonomorphismRestriction
